### ISSUE TITLE
Various exceptions when stock features disabled

### ISSUE THREAD

**Issue by escoand** [SebRut/pygrocy#79]
I tried to disable some of the stock features I don't need.

```php
# Sub feature flags
Setting('FEATURE_FLAG_STOCK_PRICE_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_LOCATION_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING', true);
Setting('FEATURE_FLAG_STOCK_PRODUCT_OPENED_TRACKING', true);
Setting('FEATURE_FLAG_STOCK_PRODUCT_FREEZING', false);
Setting('FEATURE_FLAG_SHOPPINGLIST_MULTIPLE_LISTS', false);
Setting('FEATURE_FLAG_CHORES_ASSIGNMENTS', false);
```

But this leads to various exceptions when reading the expired products:
```
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 179, in expired_products
    item.get_details(self._api_client)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 24, in get_details
    details = api_client.get_product(self.product_id)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 322, in get_product
    return ProductDetailsResponse(parsed_json)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 231, in __init__
    self._location = LocationData(parsed_json.get('location'))
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 52, in __init__
    self._id = parse_int(parsed_json.get('id'))
AttributeError: 'NoneType' object has no attribute 'get'
```

And 

```
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 199, in chores
    raw_chores = self._api_client.get_chores()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 328, in get_chores
    return [CurrentChoreResponse(chore) for chore in parsed_json]
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 328, in <listcomp>
    return [CurrentChoreResponse(chore) for chore in parsed_json]
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 156, in __init__
    self._chore_id = parse_int(parsed_json.get('chore_id'), None)
AttributeError: 'str' object has no attribute 'get'
```

**Comment by BlueBlueBlob** [comment]
Hi.
Thanks for reporting.

I will try to replicate.

Keep in touch

**Comment by BlueBlueBlob** [comment]
Fix in next release.
